version: "2"
services:
  dns_SOA_interne:
    image: resystit/bind9
    container_name: dns_SOA_interne
    ports: 
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./dns/bind:/etc/bind
      - ./dns/bind/db.wt20.ephec-ti.be:/var/cache/bind/db.wt20.ephec-ti.be
      - ./dns/resolv.conf:/etc/resolv.conf
  asterisk: 
    container_name: asterisk
    image: matiuso/debisterisk
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
    volumes: 
      - ./asterisk/users.conf:/etc/asterisk/users.conf
      - ./asterisk/sip.conf:/etc/asterisk/sip.conf
      - ./asterisk/extensions.conf:/etc/asterisk/extensions.conf
      - ./asterisk/logger.conf:/etc/asterisk/logger.conf
      - /var/log/asterisk:/var/log/asterisk
     # - ./asterisk/rtp.conf:/etc/asterisk/rtp.conf
     # - ./asterisk/pjsip.conf:/etc/asterisk/pjsip.conf
