version: '2'
services:
  dns_SOA_interne:
    image: resystit/bind9  
    container_name: dns_SOA_interne
    ports:
     - "53:53/udp"
     - "53:53/tcp"
    volumes: 
     - ./dns/bind:/etc/bind
     - ./dns/bind/db.wt20.ephec-ti.be:/var/cache/bind/db.wt20.ephec-ti.be

  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: wt20.ephec-ti.be 
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "110:110"
      - "995:995"
    volumes:
      - ./mail/ingoing:/var/mail
      - ./mail/state:/var/mail-state
      - /etc/letsencrypt:/etc/letsencrypt/
      - /etc/localtime:/etc/localtime:ro
      - ./mail/config/:/tmp/docker-mailserver/
    environment:
      - ENABLE_SPAMASSASSIN=1 # antispam
      - ENABLE_CLAMAV=1 # antivirus
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=0 # filtre par liste grise
      - ENABLE_FETCHMAIL=1
      - ENABLE_POP3=1
      - ONE_DIR=1
      - DMS_DEBUG=1 # env = dev
      - SA_TAG=2.0
      - SA_TAG2=6.31
      - SASL_PASSWD="lol"
      - SSL_TYPE=letsencrypt
  flask:
    build: 
      context: ./flask/
    environment:
      - POSTGRES_USER=woodytoys
      - POSTGRES_DB=woodytoys
      - POSTGRES_PASSWORD=super-secret-pwd
    volumes:
      - ./flask:/code
    links:
      - postgres
  postgres:
    image: postgres:alpine
    volumes:
      - ./flask/sql/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=woodytoys
      - POSTGRES_DB=woodytoys
      - POSTGRES_PASSWORD=super-secret-pwd
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/www:/var/www/
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"
    links:
      - flask
  dns:
    image: resystit/bind9
  dns_SOA_interne:
    image: resystit/bind9
    container_name: dns_SOA_interne
    ports: 
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./dns/bind:/etc/bind
      - ./dns/bind/internal.db.wt20.ephec-ti.be:/var/cache/bind/internal.db.wt20.ephec-ti.be
      - ./dns/bind/external.db.wt20.ephec-ti.be:/var/cache/bind/external.db.wt20.ephec-ti.be
      - ./dns/resolv.conf:/etc/resolv.conf
  asterisk: 
    container_name: asterisk
    image: matiuso/debisterisk
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
    volumes: 
      - ./asterisk/users.conf:/etc/asterisk/users.conf
      - ./asterisk/sip.conf:/etc/asterisk/sip.conf
      - ./asterisk/extensions.conf:/etc/asterisk/extensions.conf
      - ./asterisk/logger.conf:/etc/asterisk/logger.conf
      - ./asterisk/voicemail.conf:/etc/asterisk/voicemail.conf
      - /var/log/asterisk:/var/log/asterisk
     # - ./asterisk/rtp.conf:/etc/asterisk/rtp.conf
     # - ./asterisk/pjsip.conf:/etc/asterisk/pjsip.conf
