version: "2"
services:
  flask:
    build: 
      context: ./flask/
    environment:
      - POSTGRES_USER=woodytoys
      - POSTGRES_DB=woodytoys
      - POSTGRES_PASSWORD=super-secret-pwd
    links:
      - postgres
  postgres:
    build:
      context: ./database
    environment:
      - POSTGRES_USER=woodytoys
      - POSTGRES_DB=woodytoys
      - POSTGRES_PASSWORD=super-secret-pwd
  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/www:/var/www/
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"
    links:
      - flask
    
